name: Building Infrastructure

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout Response
              uses: actions/checkout@v2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.0.0

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  audience: sts.amazonaws.com
                  role-to-assume: arn:aws:iam::288761745617:role/Role_Elastic_deployment
                  role-session-name: GitHubActions-Terraform
                  aws-region: us-east-1

            - name: Terraform Init
              run: terraform init

            - name: Terraform Plan
              env:
                SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
              run: terraform plan -var "public_key=$SSH_PUBLIC_KEY"

